# Generated by Django 2.2.3 on 2020-05-28 08:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('LastModified', models.DateTimeField(auto_now=True)),
                ('is_current', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateTimeField(default=datetime.datetime(2020, 5, 28, 13, 38, 44, 267171))),
                ('is_free_issue', models.BooleanField(default=False)),
                ('LastModified', models.DateTimeField(auto_now=True)),
                ('free_issue_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='free_issues', to='warehouse.ProductBatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='batches', to='warehouse.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('LastModified', models.DateTimeField(auto_now=True)),
                ('is_current', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=20)),
                ('entity', models.CharField(choices=[('SEGA', 'Sega'), ('ROYALMARKETING', 'Royal Marketing'), ('CHITFUND', 'Chit Fund'), ('OTHER', 'Other')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('is_current', models.BooleanField(default=True)),
                ('LastModified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('LastModified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('LastModified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(choices=[('SEGA', 'Sega'), ('ROYALMARKETING', 'Royal Marketing'), ('CHITFUND', 'Chit Fund'), ('OTHER', 'Other')], max_length=50)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.CharField(blank=True, max_length=20, null=True)),
                ('LastModified', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Address')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseType')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('LastModified', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sell_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('initial_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_sold', models.BooleanField(default=False)),
                ('is_moved', models.BooleanField(default=False)),
                ('is_revalued', models.BooleanField(default=False)),
                ('pre_revalued_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('LastModified', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='warehouse.ProductBatch')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.Warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='productbatch',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.Supplier'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='warehouse.ProductCategory'),
        ),
        migrations.CreateModel(
            name='MovedToVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('return_date_time', models.DateTimeField(blank=True, null=True)),
                ('LastModified', models.DateTimeField(auto_now=True)),
                ('product_piece', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.ProductPiece')),
                ('return_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.Warehouse')),
                ('to_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.StockVehicle')),
            ],
        ),
        migrations.CreateModel(
            name='SalesPersonVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2020, 5, 28, 13, 38, 44, 271172))),
                ('last_modified', models.DateTimeField(default=datetime.datetime(2020, 5, 28, 13, 38, 44, 271171))),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='user.Employee')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='warehouse.Route')),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='user.Employee')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_persons', to='warehouse.StockVehicle')),
            ],
            options={
                'unique_together': {('sales_person', 'vehicle', 'driver', 'date', 'route')},
            },
        ),
    ]
