# Generated by Django 2.2.3 on 2020-05-31 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbatch',
            name='date_in',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 31, 16, 25, 55, 224190)),
        ),
        migrations.AlterField(
            model_name='salespersonvehicle',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 31, 16, 25, 55, 228189)),
        ),
        migrations.AlterField(
            model_name='salespersonvehicle',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 31, 16, 25, 55, 229189)),
        ),
    ]
