# Generated by Django 2.2.3 on 2020-05-31 13:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_auto_20200531_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movedtovehicle',
            name='LastModified',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 31, 13, 39, 5, 169812, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='date_in',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 31, 19, 9, 5, 166813)),
        ),
        migrations.AlterField(
            model_name='route',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 31, 13, 39, 5, 170814, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salespersonvehicle',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 31, 19, 9, 5, 170814)),
        ),
        migrations.AlterField(
            model_name='salespersonvehicle',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 31, 13, 39, 5, 170814, tzinfo=utc)),
        ),
    ]
