# Generated by Django 2.2.3 on 2020-05-31 13:43

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_auto_20200531_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movedtovehicle',
            name='LastModified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='date_in',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 31, 19, 13, 45, 838481)),
        ),
        migrations.AlterField(
            model_name='route',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salespersonvehicle',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salespersonvehicle',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
