# Generated by Django 2.2.3 on 2020-06-05 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20200531_1203'),
        ('warehouse', '0008_auto_20200531_2028'),
    ]

    operations = [
    ]
