# Generated by Django 2.2.3 on 2020-06-15 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_merge_20200605_1128'),
        ('warehouse', '0011_auto_20200614_2248'),
    ]

    operations = [
    ]
