# Generated by Django 2.2.3 on 2020-06-20 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0012_auto_20200616_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbatch',
            name='date_in',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 20, 23, 31, 34, 621223)),
        ),
    ]
