# Generated by Django 2.2.3 on 2020-06-19 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0013_auto_20200615_1127'),
        ('warehouse', '0012_auto_20200616_1021'),
    ]

    operations = [
    ]
