# Generated by Django 2.2.3 on 2020-06-27 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0013_auto_20200620_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbatch',
            name='date_in',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 21, 38, 57, 563207)),
        ),
    ]
