# Generated by Django 2.2.3 on 2020-06-28 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0015_auto_20200627_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbatch',
            name='date_in',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 28, 14, 39, 53, 851034)),
        ),
    ]
