# Generated by Django 2.2.3 on 2020-06-28 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0015_auto_20200628_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbatch',
            name='date_in',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 28, 15, 16, 28, 384190)),
        ),
    ]
