# Generated by Django 2.2.3 on 2020-06-28 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0016_auto_20200628_1439'),
        ('warehouse', '0016_auto_20200628_1516'),
    ]

    operations = [
    ]
