# Generated by Django 2.2.3 on 2020-06-28 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0016_auto_20200628_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbatch',
            name='date_in',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 28, 23, 0, 16, 796204)),
        ),
    ]
