# Generated by Django 2.2.3 on 2020-07-18 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0017_merge_20200628_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbatch',
            name='date_in',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 18, 3, 7, 41248)),
        ),
    ]
