# Generated by Django 2.2.3 on 2020-07-05 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0017_merge_20200628_1544'),
        ('warehouse', '0019_auto_20200628_2303'),
    ]

    operations = [
    ]
