# Generated by Django 2.2.3 on 2020-10-12 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0024_auto_20200718_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movedtovehicle',
            name='product_piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle', to='warehouse.ProductPiece'),
        ),
    ]
