# Generated by Django 2.2.3 on 2020-08-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_auto_20200816_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='total_deductions',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction')], max_length=10),
        ),
    ]
