# Generated by Django 2.2.3 on 2020-05-28 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No', models.CharField(max_length=10)),
                ('Street', models.CharField(max_length=100)),
                ('Town', models.CharField(blank=True, max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('GSDivision', models.CharField(blank=True, max_length=100, null=True)),
                ('DSDivision', models.CharField(blank=True, max_length=100, null=True)),
                ('Longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('Latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('LastModified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('PreferedName', models.CharField(blank=True, max_length=50, null=True)),
                ('ContactNo', models.CharField(max_length=20)),
                ('MobileNo', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('LastModified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIC', models.CharField(max_length=12, unique=True)),
                ('DOB', models.DateField(null=True)),
                ('Gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True)),
                ('RegisteredDate', models.DateField(default='1990-01-01')),
                ('isBlacklisted', models.BooleanField(default=False)),
                ('LastModified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_type', models.CharField(choices=[('DRIVER', 'Driver'), ('SALES PERSON', 'Sales Person'), ('MANAGER', 'Manager'), ('OFFICE STAFF', 'Office Staff')], max_length=20)),
                ('LastModified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIC', models.CharField(max_length=12, unique=True)),
                ('DOB', models.DateField(null=True)),
                ('Gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True)),
                ('LastModified', models.DateTimeField(auto_now=True)),
                ('Contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.Contact')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIC', models.CharField(max_length=12, unique=True)),
                ('DOB', models.DateField(null=True)),
                ('Gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True)),
                ('Entity', models.CharField(choices=[('SEGA', 'Sega'), ('ROYALMARKETING', 'Royal Marketing'), ('OTHER', 'Other')], max_length=50)),
                ('IsCurrent', models.BooleanField(default=True)),
                ('JoinedDate', models.DateField(default='1900-01-01')),
                ('LastModified', models.DateTimeField(auto_now=True)),
                ('Contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Contact')),
                ('EmployeeType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.EmployeeType')),
                ('Supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.Employee')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('customers', models.ManyToManyField(blank=True, null=True, related_name='customer_groups', to='user.Customer')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='leading_group', to='user.Customer')),
            ],
        ),
    ]
