# Generated by Django 2.2.3 on 2020-05-28 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customergroup',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.Product'),
        ),
        migrations.AddField(
            model_name='customer',
            name='AlternativeContact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AlternativeContact', to='user.Contact'),
        ),
        migrations.AddField(
            model_name='customer',
            name='BillingAddress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Address'),
        ),
        migrations.AddField(
            model_name='customer',
            name='Referee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Referee'),
        ),
        migrations.AddField(
            model_name='customer',
            name='RegisteredByEmployee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Employee'),
        ),
        migrations.AddField(
            model_name='customer',
            name='User',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.Contact'),
        ),
        migrations.AddField(
            model_name='customer',
            name='entity',
            field=models.ManyToManyField(to='user.Entity'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.Address'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('FirstName', 'LastName', 'Address')},
        ),
    ]
