# Generated by Django 2.2.3 on 2020-05-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200528_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='EmployeeType',
            field=models.CharField(choices=[('DRIVER', 'Driver'), ('SALES PERSON', 'Sales Person'), ('MANAGER', 'Manager'), ('OFFICE STAFF', 'Office Staff')], max_length=50),
        ),
    ]
