# Generated by Django 2.2.3 on 2020-05-31 11:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200531_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='LastModified',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 31, 11, 9, 44, 753225, tzinfo=utc)),
        ),
    ]
