# Generated by Django 2.2.3 on 2020-05-31 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200531_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='LastModified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='customers',
            field=models.ManyToManyField(related_name='customer_groups', to='user.Customer'),
        ),
    ]
