# Generated by Django 2.2.3 on 2020-05-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200531_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='entity',
        ),
        migrations.AddField(
            model_name='customer',
            name='entity',
            field=models.CharField(choices=[('SEGA', 'Sega'), ('ROYALMARKETING', 'Royal Marketing'), ('OTHER', 'Other')], default='ROYALMARKETING', max_length=50),
        ),
    ]
