# Generated by Django 2.2.3 on 2020-08-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
                ('filter_url', models.URLField()),
                ('filter_param', models.CharField(max_length=50)),
                ('value', models.CharField(default='all', max_length=50)),
            ],
        ),
    ]
