# Generated by Django 2.2.3 on 2020-08-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20200823_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='data_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='filter_url',
            field=models.CharField(max_length=200),
        ),
    ]
