# Generated by Django 2.2.3 on 2020-05-28 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('installment', '0002_installmentplan_invoice'),
        ('warehouse', '0001_initial'),
        ('sales', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnorder',
            name='product_piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.ProductPiece'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='instalment_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_receipts', to='installment.InstallmentTerm'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Order'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='sales_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='user.Employee'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='sales_person_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='warehouse.SalesPersonVehicle'),
        ),
        migrations.AddField(
            model_name='paymentbreakdown',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_breakdown', to='sales.Receipt'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderLines', to='sales.Order'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.ProductPiece'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='user.Customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_orders', to='user.CustomerGroup'),
        ),
        migrations.AddField(
            model_name='order',
            name='guarantor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='guarantor_of', to='user.Customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='sales_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='user.Employee'),
        ),
        migrations.AddField(
            model_name='order',
            name='sales_person_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='warehouse.SalesPersonVehicle'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='payment_breakdown',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheque', to='sales.PaymentBreakdown'),
        ),
    ]
