# Generated by Django 2.2.3 on 2020-06-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20200614_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnorder',
            name='action',
            field=models.CharField(choices=[('WARRANTY CLAIM', 'Warranty Claim'), ('EXCHANGE_ORDER', 'Exchange Order'), ('REFUND', 'Refund')], default='REFUND', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnorder',
            name='is_action_performed',
            field=models.BooleanField(default=False),
        ),
    ]
