# Generated by Django 2.2.3 on 2020-06-27 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20200627_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnorder',
            name='action',
            field=models.CharField(choices=[('WARRANTY CLAIM', 'Warranty Claim'), ('EXCHANGE ORDER', 'Exchange Order'), ('REFUND', 'Refund')], max_length=20),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
