# Generated by Django 2.2.3 on 2020-06-28 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0016_auto_20200628_1439'),
        ('sales', '0005_auto_20200627_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnorder',
            name='sales_person_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.SalesPersonVehicle'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_type',
            field=models.CharField(choices=[('INSTALMENT', 'Instalment'), ('INITIAL', 'Intial Payment'), ('COMPLETE', 'Complete Payment'), ('REFUND', 'Refund')], max_length=50),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='action',
            field=models.CharField(blank=True, choices=[('WARRANTY CLAIM', 'Warranty Claim'), ('EXCHANGE ORDER', 'Exchange Order'), ('REFUND', 'Refund')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='is_action_performed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
