# Generated by Django 2.2.3 on 2020-06-29 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20200628_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='parent_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_order', to='sales.Order'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='sales.Order', unique=True),
        ),
    ]
