# Generated by Django 2.2.3 on 2020-06-29 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20200629_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='sales.Order'),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Order', unique=True),
        ),
    ]
