# Generated by Django 2.2.3 on 2020-06-29 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20200629_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='order',
        ),
    ]
