# Generated by Django 2.2.3 on 2020-06-29 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_remove_receipt_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='sales.Order'),
        ),
    ]
