# Generated by Django 2.2.3 on 2020-07-05 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_auto_20200629_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Order'),
        ),
    ]
