# Generated by Django 2.2.3 on 2020-07-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_auto_20200705_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='parent_order',
        ),
    ]
