# Generated by Django 2.2.3 on 2020-05-28 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('week_day', models.CharField(choices=[('MONDAY', 'Moday'), ('TUESDAY', 'Tuesday'), ('WENDSDAY', 'Wendsday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('OVERDUE', 'Over Due'), ('COMPLETE', 'Complete'), ('ONPROCESS', 'On Process')], max_length=10, null=True)),
                ('no_of_terms', models.IntegerField(null=True)),
                ('installment_type', models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Weekly', max_length=10)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstallmentTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('due_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('due_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('last_modified', models.DateField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='installment.InstallmentPlan')),
            ],
        ),
    ]
