# Generated by Django 2.2.3 on 2020-05-31 13:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0002_installmentplan_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentplan',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='installmentterm',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='last_modified',
            field=models.DateField(default=datetime.datetime(2020, 5, 31, 13, 39, 5, 175813, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='status',
            field=models.CharField(blank=True, choices=[('OVERDUE', 'Over Due'), ('COMPLETE', 'Complete'), ('ONPROCESS', 'On Process'), ('CANCELED', 'Cancelled')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='installmentterm',
            name='last_modified',
            field=models.DateField(default=datetime.datetime(2020, 5, 31, 13, 39, 5, 176812, tzinfo=utc)),
        ),
    ]
