# Generated by Django 2.2.3 on 2020-05-31 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0003_auto_20200531_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentplan',
            name='last_modified',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='installmentterm',
            name='last_modified',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
