# Generated by Django 2.2.3 on 2020-05-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0004_auto_20200531_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentplan',
            name='status',
            field=models.CharField(blank=True, choices=[('OVERDUE', 'Over Due'), ('COMPLETE', 'Complete'), ('ONPROCESS', 'On Process'), ('CANCELLED', 'Cancelled')], max_length=10, null=True),
        ),
    ]
