# Generated by Django 2.2.3 on 2020-06-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0005_auto_20200531_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentterm',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
