# Generated by Django 2.2.3 on 2020-06-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0006_auto_20200612_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentplan',
            name='installment_type',
            field=models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='WEEKLY', max_length=10),
        ),
    ]
