# Generated by Django 2.2.3 on 2020-05-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_order', models.IntegerField()),
                ('is_delivered', models.BooleanField(default=False)),
            ],
        ),
    ]
