# Generated by Django 2.2.3 on 2020-05-28 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('sales', '0001_initial'),
        ('chitfund', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdelivery',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Customer'),
        ),
        migrations.AddField(
            model_name='customerdelivery',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.CustomerGroup'),
        ),
        migrations.AddField(
            model_name='customerdelivery',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Order'),
        ),
    ]
